### ISSUE TITLE
Question : Plugin web-application vs Structure appli

### ISSUE THREAD

**Issue by EC2311** [ericferon/glpi-archisw#31]
Hello

I wonder about setting all 'web application' applications in structure application plugin, and setting type of application as WEB in structure appli.

What is your advice ? what are your againsts and fors ;) What will you do ?

**Comment by ericferon** [comment]
I developed this plugin "archisw" because I didn't find in "webapplication" what I wanted, a.o the ability to decompose any application into its components. I missed also some interesting informations like the version, the development language, the database technology, ...
So, you are able to maintain all the information present for a "webapplication", plus a lot of other information, into "archisw".
Concerning the type, you are free to use the "type" field as you want. I used it to know whether it's a packaged or custom application, but you may add "web" if you want.
I do not use "webapplication" anymore.
Best regards,
